//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Reserva
    {
        public Nullable<int> id_reserva_d { get; set; }
        public Nullable<int> id_producto_d { get; set; }
        public int id_dr { get; set; }
        public Nullable<int> precioFinal { get; set; }
        public string nombreProd { get; set; }
    
        public virtual Reserva Reserva { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
