//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int id { get; set; }
        public string usuario1 { get; set; }
        public string pwd { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
